//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("GamblingModel", "FK_BuraGameVersion_BuraGame", "BuraGame", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GamblingModel.BuraGame), "BuraGameVersion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GamblingModel.BuraGameVersion), true)]
[assembly: EdmRelationshipAttribute("GamblingModel", "FK_BuraGameEvent_BuraGamePlayer", "BuraGamePlayer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GamblingModel.BuraGamePlayer), "BuraGameEvent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GamblingModel.BuraGameEvent), true)]
[assembly: EdmRelationshipAttribute("GamblingModel", "FK_BuraGamePlayer_BuraGame", "BuraGameVersion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GamblingModel.BuraGameVersion), "BuraGamePlayer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GamblingModel.BuraGamePlayer), true)]
[assembly: EdmRelationshipAttribute("GamblingModel", "FK_BuraGamePlayer_Player", "Player", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GamblingModel.Player), "BuraGamePlayer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GamblingModel.BuraGamePlayer), true)]
[assembly: EdmRelationshipAttribute("GamblingModel", "FK_BuraPlayerCard_GamePlayer", "BuraGamePlayer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GamblingModel.BuraGamePlayer), "BuraPlayerCard", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GamblingModel.BuraPlayerCard), true)]
[assembly: EdmRelationshipAttribute("GamblingModel", "FK_BuraPlayerPlacedCard_Player", "BuraGamePlayer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GamblingModel.BuraGamePlayer), "BuraPlayerPlacedCard", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GamblingModel.BuraPlayerPlacedCard), true)]
[assembly: EdmRelationshipAttribute("GamblingModel", "FK_BuraPlayerTakenCard_BuraGamePlayer", "BuraGamePlayer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GamblingModel.BuraGamePlayer), "BuraPlayerTakenCard", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GamblingModel.BuraPlayerTakenCard), true)]
[assembly: EdmRelationshipAttribute("GamblingModel", "FK_BuraGameVersion_LastCardTakerPlayer", "Player", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GamblingModel.Player), "BuraGameVersion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GamblingModel.BuraGameVersion), true)]
[assembly: EdmRelationshipAttribute("GamblingModel", "FK_BuraGameVersion_LastDoublingOffererPlayer", "Player", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GamblingModel.Player), "BuraGameVersion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GamblingModel.BuraGameVersion), true)]
[assembly: EdmRelationshipAttribute("GamblingModel", "FK_BuraGameVersion_PlayerTurn", "Player", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GamblingModel.Player), "BuraGameVersion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GamblingModel.BuraGameVersion), true)]
[assembly: EdmRelationshipAttribute("GamblingModel", "FK_BuraGameVersion_PreviousCardTakerPlayer", "Player", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GamblingModel.Player), "BuraGameVersion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GamblingModel.BuraGameVersion), true)]

#endregion

namespace GamblingModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BuraGame> BuraGames
        {
            get
            {
                if ((_BuraGames == null))
                {
                    _BuraGames = base.CreateObjectSet<BuraGame>("BuraGames");
                }
                return _BuraGames;
            }
        }
        private ObjectSet<BuraGame> _BuraGames;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BuraGameEvent> BuraGameEvents
        {
            get
            {
                if ((_BuraGameEvents == null))
                {
                    _BuraGameEvents = base.CreateObjectSet<BuraGameEvent>("BuraGameEvents");
                }
                return _BuraGameEvents;
            }
        }
        private ObjectSet<BuraGameEvent> _BuraGameEvents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BuraGamePlayer> BuraGamePlayers
        {
            get
            {
                if ((_BuraGamePlayers == null))
                {
                    _BuraGamePlayers = base.CreateObjectSet<BuraGamePlayer>("BuraGamePlayers");
                }
                return _BuraGamePlayers;
            }
        }
        private ObjectSet<BuraGamePlayer> _BuraGamePlayers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BuraGameVersion> BuraGameVersions
        {
            get
            {
                if ((_BuraGameVersions == null))
                {
                    _BuraGameVersions = base.CreateObjectSet<BuraGameVersion>("BuraGameVersions");
                }
                return _BuraGameVersions;
            }
        }
        private ObjectSet<BuraGameVersion> _BuraGameVersions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BuraPlayerCard> BuraPlayerCards
        {
            get
            {
                if ((_BuraPlayerCards == null))
                {
                    _BuraPlayerCards = base.CreateObjectSet<BuraPlayerCard>("BuraPlayerCards");
                }
                return _BuraPlayerCards;
            }
        }
        private ObjectSet<BuraPlayerCard> _BuraPlayerCards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BuraPlayerPlacedCard> BuraPlayerPlacedCards
        {
            get
            {
                if ((_BuraPlayerPlacedCards == null))
                {
                    _BuraPlayerPlacedCards = base.CreateObjectSet<BuraPlayerPlacedCard>("BuraPlayerPlacedCards");
                }
                return _BuraPlayerPlacedCards;
            }
        }
        private ObjectSet<BuraPlayerPlacedCard> _BuraPlayerPlacedCards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BuraPlayerTakenCard> BuraPlayerTakenCards
        {
            get
            {
                if ((_BuraPlayerTakenCards == null))
                {
                    _BuraPlayerTakenCards = base.CreateObjectSet<BuraPlayerTakenCard>("BuraPlayerTakenCards");
                }
                return _BuraPlayerTakenCards;
            }
        }
        private ObjectSet<BuraPlayerTakenCard> _BuraPlayerTakenCards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Player> Players
        {
            get
            {
                if ((_Players == null))
                {
                    _Players = base.CreateObjectSet<Player>("Players");
                }
                return _Players;
            }
        }
        private ObjectSet<Player> _Players;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BuraGames EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBuraGames(BuraGame buraGame)
        {
            base.AddObject("BuraGames", buraGame);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BuraGameEvents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBuraGameEvents(BuraGameEvent buraGameEvent)
        {
            base.AddObject("BuraGameEvents", buraGameEvent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BuraGamePlayers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBuraGamePlayers(BuraGamePlayer buraGamePlayer)
        {
            base.AddObject("BuraGamePlayers", buraGamePlayer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BuraGameVersions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBuraGameVersions(BuraGameVersion buraGameVersion)
        {
            base.AddObject("BuraGameVersions", buraGameVersion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BuraPlayerCards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBuraPlayerCards(BuraPlayerCard buraPlayerCard)
        {
            base.AddObject("BuraPlayerCards", buraPlayerCard);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BuraPlayerPlacedCards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBuraPlayerPlacedCards(BuraPlayerPlacedCard buraPlayerPlacedCard)
        {
            base.AddObject("BuraPlayerPlacedCards", buraPlayerPlacedCard);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BuraPlayerTakenCards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBuraPlayerTakenCards(BuraPlayerTakenCard buraPlayerTakenCard)
        {
            base.AddObject("BuraPlayerTakenCards", buraPlayerTakenCard);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Players EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPlayers(Player player)
        {
            base.AddObject("Players", player);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GamblingModel", Name="BuraGame")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BuraGame : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BuraGame object.
        /// </summary>
        /// <param name="gameId">Initial value of the GameId property.</param>
        /// <param name="longStyle">Initial value of the LongStyle property.</param>
        /// <param name="passHiddenCards">Initial value of the PassHiddenCards property.</param>
        /// <param name="stickAllowed">Initial value of the StickAllowed property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="playTill">Initial value of the PlayTill property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        public static BuraGame CreateBuraGame(global::System.Int32 gameId, global::System.Boolean longStyle, global::System.Boolean passHiddenCards, global::System.Boolean stickAllowed, global::System.Double amount, global::System.Int32 playTill, global::System.DateTime startDate)
        {
            BuraGame buraGame = new BuraGame();
            buraGame.GameId = gameId;
            buraGame.LongStyle = longStyle;
            buraGame.PassHiddenCards = passHiddenCards;
            buraGame.StickAllowed = stickAllowed;
            buraGame.Amount = amount;
            buraGame.PlayTill = playTill;
            buraGame.StartDate = startDate;
            return buraGame;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GameId
        {
            get
            {
                return _GameId;
            }
            set
            {
                if (_GameId != value)
                {
                    OnGameIdChanging(value);
                    ReportPropertyChanging("GameId");
                    _GameId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GameId");
                    OnGameIdChanged();
                }
            }
        }
        private global::System.Int32 _GameId;
        partial void OnGameIdChanging(global::System.Int32 value);
        partial void OnGameIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LongStyle
        {
            get
            {
                return _LongStyle;
            }
            set
            {
                OnLongStyleChanging(value);
                ReportPropertyChanging("LongStyle");
                _LongStyle = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LongStyle");
                OnLongStyleChanged();
            }
        }
        private global::System.Boolean _LongStyle;
        partial void OnLongStyleChanging(global::System.Boolean value);
        partial void OnLongStyleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PassHiddenCards
        {
            get
            {
                return _PassHiddenCards;
            }
            set
            {
                OnPassHiddenCardsChanging(value);
                ReportPropertyChanging("PassHiddenCards");
                _PassHiddenCards = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PassHiddenCards");
                OnPassHiddenCardsChanged();
            }
        }
        private global::System.Boolean _PassHiddenCards;
        partial void OnPassHiddenCardsChanging(global::System.Boolean value);
        partial void OnPassHiddenCardsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean StickAllowed
        {
            get
            {
                return _StickAllowed;
            }
            set
            {
                OnStickAllowedChanging(value);
                ReportPropertyChanging("StickAllowed");
                _StickAllowed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StickAllowed");
                OnStickAllowedChanged();
            }
        }
        private global::System.Boolean _StickAllowed;
        partial void OnStickAllowedChanging(global::System.Boolean value);
        partial void OnStickAllowedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Double _Amount;
        partial void OnAmountChanging(global::System.Double value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlayTill
        {
            get
            {
                return _PlayTill;
            }
            set
            {
                OnPlayTillChanging(value);
                ReportPropertyChanging("PlayTill");
                _PlayTill = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlayTill");
                OnPlayTillChanged();
            }
        }
        private global::System.Int32 _PlayTill;
        partial void OnPlayTillChanging(global::System.Int32 value);
        partial void OnPlayTillChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GamblingModel", "FK_BuraGameVersion_BuraGame", "BuraGameVersion")]
        public EntityCollection<BuraGameVersion> BuraGameVersions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BuraGameVersion>("GamblingModel.FK_BuraGameVersion_BuraGame", "BuraGameVersion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BuraGameVersion>("GamblingModel.FK_BuraGameVersion_BuraGame", "BuraGameVersion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GamblingModel", Name="BuraGameEvent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BuraGameEvent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BuraGameEvent object.
        /// </summary>
        /// <param name="buraGameEventId">Initial value of the BuraGameEventId property.</param>
        /// <param name="buraGamePlayerId">Initial value of the BuraGamePlayerId property.</param>
        /// <param name="eventId">Initial value of the EventId property.</param>
        /// <param name="eventType">Initial value of the EventType property.</param>
        /// <param name="isEventPlayed">Initial value of the IsEventPlayed property.</param>
        public static BuraGameEvent CreateBuraGameEvent(global::System.Int32 buraGameEventId, global::System.Int32 buraGamePlayerId, global::System.Int32 eventId, global::System.String eventType, global::System.Boolean isEventPlayed)
        {
            BuraGameEvent buraGameEvent = new BuraGameEvent();
            buraGameEvent.BuraGameEventId = buraGameEventId;
            buraGameEvent.BuraGamePlayerId = buraGamePlayerId;
            buraGameEvent.EventId = eventId;
            buraGameEvent.EventType = eventType;
            buraGameEvent.IsEventPlayed = isEventPlayed;
            return buraGameEvent;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BuraGameEventId
        {
            get
            {
                return _BuraGameEventId;
            }
            set
            {
                if (_BuraGameEventId != value)
                {
                    OnBuraGameEventIdChanging(value);
                    ReportPropertyChanging("BuraGameEventId");
                    _BuraGameEventId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BuraGameEventId");
                    OnBuraGameEventIdChanged();
                }
            }
        }
        private global::System.Int32 _BuraGameEventId;
        partial void OnBuraGameEventIdChanging(global::System.Int32 value);
        partial void OnBuraGameEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BuraGamePlayerId
        {
            get
            {
                return _BuraGamePlayerId;
            }
            set
            {
                OnBuraGamePlayerIdChanging(value);
                ReportPropertyChanging("BuraGamePlayerId");
                _BuraGamePlayerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuraGamePlayerId");
                OnBuraGamePlayerIdChanged();
            }
        }
        private global::System.Int32 _BuraGamePlayerId;
        partial void OnBuraGamePlayerIdChanging(global::System.Int32 value);
        partial void OnBuraGamePlayerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventId
        {
            get
            {
                return _EventId;
            }
            set
            {
                OnEventIdChanging(value);
                ReportPropertyChanging("EventId");
                _EventId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventId");
                OnEventIdChanged();
            }
        }
        private global::System.Int32 _EventId;
        partial void OnEventIdChanging(global::System.Int32 value);
        partial void OnEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EventType
        {
            get
            {
                return _EventType;
            }
            set
            {
                OnEventTypeChanging(value);
                ReportPropertyChanging("EventType");
                _EventType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EventType");
                OnEventTypeChanged();
            }
        }
        private global::System.String _EventType;
        partial void OnEventTypeChanging(global::System.String value);
        partial void OnEventTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EventValue
        {
            get
            {
                return _EventValue;
            }
            set
            {
                OnEventValueChanging(value);
                ReportPropertyChanging("EventValue");
                _EventValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventValue");
                OnEventValueChanged();
            }
        }
        private global::System.String _EventValue;
        partial void OnEventValueChanging(global::System.String value);
        partial void OnEventValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEventPlayed
        {
            get
            {
                return _IsEventPlayed;
            }
            set
            {
                OnIsEventPlayedChanging(value);
                ReportPropertyChanging("IsEventPlayed");
                _IsEventPlayed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEventPlayed");
                OnIsEventPlayedChanged();
            }
        }
        private global::System.Boolean _IsEventPlayed;
        partial void OnIsEventPlayedChanging(global::System.Boolean value);
        partial void OnIsEventPlayedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GamblingModel", Name="BuraGamePlayer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BuraGamePlayer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BuraGamePlayer object.
        /// </summary>
        /// <param name="buraGamePlayerId">Initial value of the BuraGamePlayerId property.</param>
        /// <param name="gameId">Initial value of the GameId property.</param>
        /// <param name="versionNumber">Initial value of the VersionNumber property.</param>
        /// <param name="playerId">Initial value of the PlayerId property.</param>
        /// <param name="playerScore">Initial value of the PlayerScore property.</param>
        public static BuraGamePlayer CreateBuraGamePlayer(global::System.Int32 buraGamePlayerId, global::System.Int32 gameId, global::System.Int32 versionNumber, global::System.Int32 playerId, global::System.Int32 playerScore)
        {
            BuraGamePlayer buraGamePlayer = new BuraGamePlayer();
            buraGamePlayer.BuraGamePlayerId = buraGamePlayerId;
            buraGamePlayer.GameId = gameId;
            buraGamePlayer.VersionNumber = versionNumber;
            buraGamePlayer.PlayerId = playerId;
            buraGamePlayer.PlayerScore = playerScore;
            return buraGamePlayer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BuraGamePlayerId
        {
            get
            {
                return _BuraGamePlayerId;
            }
            set
            {
                if (_BuraGamePlayerId != value)
                {
                    OnBuraGamePlayerIdChanging(value);
                    ReportPropertyChanging("BuraGamePlayerId");
                    _BuraGamePlayerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BuraGamePlayerId");
                    OnBuraGamePlayerIdChanged();
                }
            }
        }
        private global::System.Int32 _BuraGamePlayerId;
        partial void OnBuraGamePlayerIdChanging(global::System.Int32 value);
        partial void OnBuraGamePlayerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GameId
        {
            get
            {
                return _GameId;
            }
            set
            {
                OnGameIdChanging(value);
                ReportPropertyChanging("GameId");
                _GameId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GameId");
                OnGameIdChanged();
            }
        }
        private global::System.Int32 _GameId;
        partial void OnGameIdChanging(global::System.Int32 value);
        partial void OnGameIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VersionNumber
        {
            get
            {
                return _VersionNumber;
            }
            set
            {
                OnVersionNumberChanging(value);
                ReportPropertyChanging("VersionNumber");
                _VersionNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VersionNumber");
                OnVersionNumberChanged();
            }
        }
        private global::System.Int32 _VersionNumber;
        partial void OnVersionNumberChanging(global::System.Int32 value);
        partial void OnVersionNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlayerId
        {
            get
            {
                return _PlayerId;
            }
            set
            {
                OnPlayerIdChanging(value);
                ReportPropertyChanging("PlayerId");
                _PlayerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlayerId");
                OnPlayerIdChanged();
            }
        }
        private global::System.Int32 _PlayerId;
        partial void OnPlayerIdChanging(global::System.Int32 value);
        partial void OnPlayerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlayerScore
        {
            get
            {
                return _PlayerScore;
            }
            set
            {
                OnPlayerScoreChanging(value);
                ReportPropertyChanging("PlayerScore");
                _PlayerScore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlayerScore");
                OnPlayerScoreChanged();
            }
        }
        private global::System.Int32 _PlayerScore;
        partial void OnPlayerScoreChanging(global::System.Int32 value);
        partial void OnPlayerScoreChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GamblingModel", "FK_BuraGameEvent_BuraGamePlayer", "BuraGameEvent")]
        public EntityCollection<BuraGameEvent> Events
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BuraGameEvent>("GamblingModel.FK_BuraGameEvent_BuraGamePlayer", "BuraGameEvent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BuraGameEvent>("GamblingModel.FK_BuraGameEvent_BuraGamePlayer", "BuraGameEvent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GamblingModel", "FK_BuraGamePlayer_Player", "Player")]
        public Player Player
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGamePlayer_Player", "Player").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGamePlayer_Player", "Player").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Player> PlayerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGamePlayer_Player", "Player");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Player>("GamblingModel.FK_BuraGamePlayer_Player", "Player", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GamblingModel", "FK_BuraPlayerCard_GamePlayer", "BuraPlayerCard")]
        public EntityCollection<BuraPlayerCard> PlayerCards
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BuraPlayerCard>("GamblingModel.FK_BuraPlayerCard_GamePlayer", "BuraPlayerCard");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BuraPlayerCard>("GamblingModel.FK_BuraPlayerCard_GamePlayer", "BuraPlayerCard", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GamblingModel", "FK_BuraPlayerPlacedCard_Player", "BuraPlayerPlacedCard")]
        public EntityCollection<BuraPlayerPlacedCard> PlacedCards
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BuraPlayerPlacedCard>("GamblingModel.FK_BuraPlayerPlacedCard_Player", "BuraPlayerPlacedCard");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BuraPlayerPlacedCard>("GamblingModel.FK_BuraPlayerPlacedCard_Player", "BuraPlayerPlacedCard", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GamblingModel", "FK_BuraPlayerTakenCard_BuraGamePlayer", "BuraPlayerTakenCard")]
        public EntityCollection<BuraPlayerTakenCard> TakenCards
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BuraPlayerTakenCard>("GamblingModel.FK_BuraPlayerTakenCard_BuraGamePlayer", "BuraPlayerTakenCard");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BuraPlayerTakenCard>("GamblingModel.FK_BuraPlayerTakenCard_BuraGamePlayer", "BuraPlayerTakenCard", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GamblingModel", Name="BuraGameVersion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BuraGameVersion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BuraGameVersion object.
        /// </summary>
        /// <param name="gameId">Initial value of the GameId property.</param>
        /// <param name="versionNumber">Initial value of the VersionNumber property.</param>
        /// <param name="gameStatus">Initial value of the GameStatus property.</param>
        /// <param name="playerHasTimeouted">Initial value of the PlayerHasTimeouted property.</param>
        /// <param name="doublingValue">Initial value of the DoublingValue property.</param>
        /// <param name="dealingCardCount">Initial value of the DealingCardCount property.</param>
        public static BuraGameVersion CreateBuraGameVersion(global::System.Int32 gameId, global::System.Int32 versionNumber, global::System.String gameStatus, global::System.Boolean playerHasTimeouted, global::System.Int32 doublingValue, global::System.Int32 dealingCardCount)
        {
            BuraGameVersion buraGameVersion = new BuraGameVersion();
            buraGameVersion.GameId = gameId;
            buraGameVersion.VersionNumber = versionNumber;
            buraGameVersion.GameStatus = gameStatus;
            buraGameVersion.PlayerHasTimeouted = playerHasTimeouted;
            buraGameVersion.DoublingValue = doublingValue;
            buraGameVersion.DealingCardCount = dealingCardCount;
            return buraGameVersion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GameId
        {
            get
            {
                return _GameId;
            }
            set
            {
                if (_GameId != value)
                {
                    OnGameIdChanging(value);
                    ReportPropertyChanging("GameId");
                    _GameId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GameId");
                    OnGameIdChanged();
                }
            }
        }
        private global::System.Int32 _GameId;
        partial void OnGameIdChanging(global::System.Int32 value);
        partial void OnGameIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VersionNumber
        {
            get
            {
                return _VersionNumber;
            }
            set
            {
                if (_VersionNumber != value)
                {
                    OnVersionNumberChanging(value);
                    ReportPropertyChanging("VersionNumber");
                    _VersionNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VersionNumber");
                    OnVersionNumberChanged();
                }
            }
        }
        private global::System.Int32 _VersionNumber;
        partial void OnVersionNumberChanging(global::System.Int32 value);
        partial void OnVersionNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GameStatus
        {
            get
            {
                return _GameStatus;
            }
            set
            {
                OnGameStatusChanging(value);
                ReportPropertyChanging("GameStatus");
                _GameStatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GameStatus");
                OnGameStatusChanged();
            }
        }
        private global::System.String _GameStatus;
        partial void OnGameStatusChanging(global::System.String value);
        partial void OnGameStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Trump
        {
            get
            {
                return _Trump;
            }
            set
            {
                OnTrumpChanging(value);
                ReportPropertyChanging("Trump");
                _Trump = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Trump");
                OnTrumpChanged();
            }
        }
        private global::System.String _Trump;
        partial void OnTrumpChanging(global::System.String value);
        partial void OnTrumpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PlayerTurn
        {
            get
            {
                return _PlayerTurn;
            }
            set
            {
                OnPlayerTurnChanging(value);
                ReportPropertyChanging("PlayerTurn");
                _PlayerTurn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlayerTurn");
                OnPlayerTurnChanged();
            }
        }
        private Nullable<global::System.Int32> _PlayerTurn;
        partial void OnPlayerTurnChanging(Nullable<global::System.Int32> value);
        partial void OnPlayerTurnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LastCardTakerPlayer
        {
            get
            {
                return _LastCardTakerPlayer;
            }
            set
            {
                OnLastCardTakerPlayerChanging(value);
                ReportPropertyChanging("LastCardTakerPlayer");
                _LastCardTakerPlayer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastCardTakerPlayer");
                OnLastCardTakerPlayerChanged();
            }
        }
        private Nullable<global::System.Int32> _LastCardTakerPlayer;
        partial void OnLastCardTakerPlayerChanging(Nullable<global::System.Int32> value);
        partial void OnLastCardTakerPlayerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PreviousCardTakerPlayer
        {
            get
            {
                return _PreviousCardTakerPlayer;
            }
            set
            {
                OnPreviousCardTakerPlayerChanging(value);
                ReportPropertyChanging("PreviousCardTakerPlayer");
                _PreviousCardTakerPlayer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PreviousCardTakerPlayer");
                OnPreviousCardTakerPlayerChanged();
            }
        }
        private Nullable<global::System.Int32> _PreviousCardTakerPlayer;
        partial void OnPreviousCardTakerPlayerChanging(Nullable<global::System.Int32> value);
        partial void OnPreviousCardTakerPlayerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PlayerHasTimeouted
        {
            get
            {
                return _PlayerHasTimeouted;
            }
            set
            {
                OnPlayerHasTimeoutedChanging(value);
                ReportPropertyChanging("PlayerHasTimeouted");
                _PlayerHasTimeouted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlayerHasTimeouted");
                OnPlayerHasTimeoutedChanged();
            }
        }
        private global::System.Boolean _PlayerHasTimeouted;
        partial void OnPlayerHasTimeoutedChanging(global::System.Boolean value);
        partial void OnPlayerHasTimeoutedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DoublingValue
        {
            get
            {
                return _DoublingValue;
            }
            set
            {
                OnDoublingValueChanging(value);
                ReportPropertyChanging("DoublingValue");
                _DoublingValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DoublingValue");
                OnDoublingValueChanged();
            }
        }
        private global::System.Int32 _DoublingValue;
        partial void OnDoublingValueChanging(global::System.Int32 value);
        partial void OnDoublingValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LastDoublingOfferer
        {
            get
            {
                return _LastDoublingOfferer;
            }
            set
            {
                OnLastDoublingOffererChanging(value);
                ReportPropertyChanging("LastDoublingOfferer");
                _LastDoublingOfferer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastDoublingOfferer");
                OnLastDoublingOffererChanged();
            }
        }
        private Nullable<global::System.Int32> _LastDoublingOfferer;
        partial void OnLastDoublingOffererChanging(Nullable<global::System.Int32> value);
        partial void OnLastDoublingOffererChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DealingCardCount
        {
            get
            {
                return _DealingCardCount;
            }
            set
            {
                OnDealingCardCountChanging(value);
                ReportPropertyChanging("DealingCardCount");
                _DealingCardCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DealingCardCount");
                OnDealingCardCountChanged();
            }
        }
        private global::System.Int32 _DealingCardCount;
        partial void OnDealingCardCountChanging(global::System.Int32 value);
        partial void OnDealingCardCountChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GamblingModel", "FK_BuraGamePlayer_BuraGame", "BuraGamePlayer")]
        public EntityCollection<BuraGamePlayer> BuraGamePlayers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BuraGamePlayer>("GamblingModel.FK_BuraGamePlayer_BuraGame", "BuraGamePlayer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BuraGamePlayer>("GamblingModel.FK_BuraGamePlayer_BuraGame", "BuraGamePlayer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GamblingModel", "FK_BuraGameVersion_LastCardTakerPlayer", "Player")]
        public Player LastCardTaker
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_LastCardTakerPlayer", "Player").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_LastCardTakerPlayer", "Player").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Player> LastCardTakerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_LastCardTakerPlayer", "Player");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_LastCardTakerPlayer", "Player", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GamblingModel", "FK_BuraGameVersion_LastDoublingOffererPlayer", "Player")]
        public Player DoublingOfferer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_LastDoublingOffererPlayer", "Player").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_LastDoublingOffererPlayer", "Player").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Player> DoublingOffererReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_LastDoublingOffererPlayer", "Player");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_LastDoublingOffererPlayer", "Player", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GamblingModel", "FK_BuraGameVersion_PlayerTurn", "Player")]
        public Player CurrentTurn
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_PlayerTurn", "Player").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_PlayerTurn", "Player").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Player> CurrentTurnReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_PlayerTurn", "Player");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_PlayerTurn", "Player", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GamblingModel", "FK_BuraGameVersion_PreviousCardTakerPlayer", "Player")]
        public Player PreviousCardTaker
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_PreviousCardTakerPlayer", "Player").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_PreviousCardTakerPlayer", "Player").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Player> PreviousCardTakerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_PreviousCardTakerPlayer", "Player");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Player>("GamblingModel.FK_BuraGameVersion_PreviousCardTakerPlayer", "Player", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GamblingModel", Name="BuraPlayerCard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BuraPlayerCard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BuraPlayerCard object.
        /// </summary>
        /// <param name="playerCardId">Initial value of the PlayerCardId property.</param>
        /// <param name="buraGamePlayerId">Initial value of the BuraGamePlayerId property.</param>
        /// <param name="cardName">Initial value of the CardName property.</param>
        public static BuraPlayerCard CreateBuraPlayerCard(global::System.Int32 playerCardId, global::System.Int32 buraGamePlayerId, global::System.String cardName)
        {
            BuraPlayerCard buraPlayerCard = new BuraPlayerCard();
            buraPlayerCard.PlayerCardId = playerCardId;
            buraPlayerCard.BuraGamePlayerId = buraGamePlayerId;
            buraPlayerCard.CardName = cardName;
            return buraPlayerCard;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlayerCardId
        {
            get
            {
                return _PlayerCardId;
            }
            set
            {
                if (_PlayerCardId != value)
                {
                    OnPlayerCardIdChanging(value);
                    ReportPropertyChanging("PlayerCardId");
                    _PlayerCardId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PlayerCardId");
                    OnPlayerCardIdChanged();
                }
            }
        }
        private global::System.Int32 _PlayerCardId;
        partial void OnPlayerCardIdChanging(global::System.Int32 value);
        partial void OnPlayerCardIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BuraGamePlayerId
        {
            get
            {
                return _BuraGamePlayerId;
            }
            set
            {
                OnBuraGamePlayerIdChanging(value);
                ReportPropertyChanging("BuraGamePlayerId");
                _BuraGamePlayerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuraGamePlayerId");
                OnBuraGamePlayerIdChanged();
            }
        }
        private global::System.Int32 _BuraGamePlayerId;
        partial void OnBuraGamePlayerIdChanging(global::System.Int32 value);
        partial void OnBuraGamePlayerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CardName
        {
            get
            {
                return _CardName;
            }
            set
            {
                OnCardNameChanging(value);
                ReportPropertyChanging("CardName");
                _CardName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CardName");
                OnCardNameChanged();
            }
        }
        private global::System.String _CardName;
        partial void OnCardNameChanging(global::System.String value);
        partial void OnCardNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GamblingModel", Name="BuraPlayerPlacedCard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BuraPlayerPlacedCard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BuraPlayerPlacedCard object.
        /// </summary>
        /// <param name="placedCardId">Initial value of the PlacedCardId property.</param>
        /// <param name="buraGamePlayerId">Initial value of the BuraGamePlayerId property.</param>
        /// <param name="cardName">Initial value of the CardName property.</param>
        public static BuraPlayerPlacedCard CreateBuraPlayerPlacedCard(global::System.Int32 placedCardId, global::System.Int32 buraGamePlayerId, global::System.String cardName)
        {
            BuraPlayerPlacedCard buraPlayerPlacedCard = new BuraPlayerPlacedCard();
            buraPlayerPlacedCard.PlacedCardId = placedCardId;
            buraPlayerPlacedCard.BuraGamePlayerId = buraGamePlayerId;
            buraPlayerPlacedCard.CardName = cardName;
            return buraPlayerPlacedCard;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlacedCardId
        {
            get
            {
                return _PlacedCardId;
            }
            set
            {
                if (_PlacedCardId != value)
                {
                    OnPlacedCardIdChanging(value);
                    ReportPropertyChanging("PlacedCardId");
                    _PlacedCardId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PlacedCardId");
                    OnPlacedCardIdChanged();
                }
            }
        }
        private global::System.Int32 _PlacedCardId;
        partial void OnPlacedCardIdChanging(global::System.Int32 value);
        partial void OnPlacedCardIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BuraGamePlayerId
        {
            get
            {
                return _BuraGamePlayerId;
            }
            set
            {
                OnBuraGamePlayerIdChanging(value);
                ReportPropertyChanging("BuraGamePlayerId");
                _BuraGamePlayerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuraGamePlayerId");
                OnBuraGamePlayerIdChanged();
            }
        }
        private global::System.Int32 _BuraGamePlayerId;
        partial void OnBuraGamePlayerIdChanging(global::System.Int32 value);
        partial void OnBuraGamePlayerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CardName
        {
            get
            {
                return _CardName;
            }
            set
            {
                OnCardNameChanging(value);
                ReportPropertyChanging("CardName");
                _CardName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CardName");
                OnCardNameChanged();
            }
        }
        private global::System.String _CardName;
        partial void OnCardNameChanging(global::System.String value);
        partial void OnCardNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GamblingModel", Name="BuraPlayerTakenCard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BuraPlayerTakenCard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BuraPlayerTakenCard object.
        /// </summary>
        /// <param name="takenCardId">Initial value of the TakenCardId property.</param>
        /// <param name="buraGamePlayerId">Initial value of the BuraGamePlayerId property.</param>
        /// <param name="cardName">Initial value of the CardName property.</param>
        /// <param name="cardValue">Initial value of the CardValue property.</param>
        public static BuraPlayerTakenCard CreateBuraPlayerTakenCard(global::System.Int32 takenCardId, global::System.Int32 buraGamePlayerId, global::System.String cardName, global::System.Int32 cardValue)
        {
            BuraPlayerTakenCard buraPlayerTakenCard = new BuraPlayerTakenCard();
            buraPlayerTakenCard.TakenCardId = takenCardId;
            buraPlayerTakenCard.BuraGamePlayerId = buraGamePlayerId;
            buraPlayerTakenCard.CardName = cardName;
            buraPlayerTakenCard.CardValue = cardValue;
            return buraPlayerTakenCard;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TakenCardId
        {
            get
            {
                return _TakenCardId;
            }
            set
            {
                if (_TakenCardId != value)
                {
                    OnTakenCardIdChanging(value);
                    ReportPropertyChanging("TakenCardId");
                    _TakenCardId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TakenCardId");
                    OnTakenCardIdChanged();
                }
            }
        }
        private global::System.Int32 _TakenCardId;
        partial void OnTakenCardIdChanging(global::System.Int32 value);
        partial void OnTakenCardIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BuraGamePlayerId
        {
            get
            {
                return _BuraGamePlayerId;
            }
            set
            {
                OnBuraGamePlayerIdChanging(value);
                ReportPropertyChanging("BuraGamePlayerId");
                _BuraGamePlayerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuraGamePlayerId");
                OnBuraGamePlayerIdChanged();
            }
        }
        private global::System.Int32 _BuraGamePlayerId;
        partial void OnBuraGamePlayerIdChanging(global::System.Int32 value);
        partial void OnBuraGamePlayerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CardName
        {
            get
            {
                return _CardName;
            }
            set
            {
                OnCardNameChanging(value);
                ReportPropertyChanging("CardName");
                _CardName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CardName");
                OnCardNameChanged();
            }
        }
        private global::System.String _CardName;
        partial void OnCardNameChanging(global::System.String value);
        partial void OnCardNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardValue
        {
            get
            {
                return _CardValue;
            }
            set
            {
                OnCardValueChanging(value);
                ReportPropertyChanging("CardValue");
                _CardValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CardValue");
                OnCardValueChanged();
            }
        }
        private global::System.Int32 _CardValue;
        partial void OnCardValueChanging(global::System.Int32 value);
        partial void OnCardValueChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GamblingModel", Name="Player")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Player : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Player object.
        /// </summary>
        /// <param name="playerId">Initial value of the PlayerId property.</param>
        /// <param name="clientId">Initial value of the ClientId property.</param>
        /// <param name="playerName">Initial value of the PlayerName property.</param>
        public static Player CreatePlayer(global::System.Int32 playerId, global::System.Int32 clientId, global::System.String playerName)
        {
            Player player = new Player();
            player.PlayerId = playerId;
            player.ClientId = clientId;
            player.PlayerName = playerName;
            return player;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlayerId
        {
            get
            {
                return _PlayerId;
            }
            set
            {
                if (_PlayerId != value)
                {
                    OnPlayerIdChanging(value);
                    ReportPropertyChanging("PlayerId");
                    _PlayerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PlayerId");
                    OnPlayerIdChanged();
                }
            }
        }
        private global::System.Int32 _PlayerId;
        partial void OnPlayerIdChanging(global::System.Int32 value);
        partial void OnPlayerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                OnClientIdChanging(value);
                ReportPropertyChanging("ClientId");
                _ClientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientId");
                OnClientIdChanged();
            }
        }
        private global::System.Int32 _ClientId;
        partial void OnClientIdChanging(global::System.Int32 value);
        partial void OnClientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PlayerName
        {
            get
            {
                return _PlayerName;
            }
            set
            {
                OnPlayerNameChanging(value);
                ReportPropertyChanging("PlayerName");
                _PlayerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PlayerName");
                OnPlayerNameChanged();
            }
        }
        private global::System.String _PlayerName;
        partial void OnPlayerNameChanging(global::System.String value);
        partial void OnPlayerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] PlayerAvatar
        {
            get
            {
                return StructuralObject.GetValidValue(_PlayerAvatar);
            }
            set
            {
                OnPlayerAvatarChanging(value);
                ReportPropertyChanging("PlayerAvatar");
                _PlayerAvatar = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PlayerAvatar");
                OnPlayerAvatarChanged();
            }
        }
        private global::System.Byte[] _PlayerAvatar;
        partial void OnPlayerAvatarChanging(global::System.Byte[] value);
        partial void OnPlayerAvatarChanged();

        #endregion

    
    }

    #endregion

    
}
